export const ImageListPopular = [
   "/img/main/Craz.jpg",
   "/img/main/element.jpg",
   "/img/main/BronzeChairs.jpg",
   "/img/main/DressColour.jpg",
];
export const ImageListBW = [
   "/img/main/Banister.jpg",
   "/img/main/DoorCeiling.jpg",
   "/img/main/Arches.jpg",
   "/img/main/Ediface.jpg",
   "/img/main/NewZealandShadow.jpg",
];
export const ImageListNature = [
   "/img/main/YellowFlowers.jpg",
   "/img/main/PurpleFlowers.jpg",
   "/img/main/PinkFlower.jpg",
   "/img/main/Paulonia.jpg",
   "/img/main/PrimordialSwamp.jpg",
   "/img/main/TreeArch.jpg",
   "/img/main/Green.jpg",
   "/img/main/Starlings.jpg",
];
export const ImageListViews = [
   "/img/main/Surfer.jpg",
   "/img/main/SeaSkyCloud.jpg",
   "/img/main/EightArchBridge.jpg",
   "/img/main/RaceTrack.jpg",
   "/img/main/WindscreenSunset.jpg",
   "/img/main/DrWhoSet.jpg",
   "/img/main/Sexism.jpg",
   "/img/main/Wall.jpg",
   "/img/main/NoFilters.jpg",
   "/img/main/Pillbox.jpg",
   "/img/main/BuildingSite.jpg",
   "/img/main/GreyDay.jpg",
   "/img/main/Sunset.jpg",
   "/img/main/BeachLong.jpg",
   "/img/main/SeaSky.jpg",
   "/img/main/Beach.jpg",
];
export const ImageListOddities = [
   "/img/main/SpotTheSheep.jpg",
   "/img/main/SpotTheDolly.jpg",
   "/img/main/SantaDalek.jpg",
   "/img/main/MysteryDalek.jpg",
   "/img/main/GetOutaHere.jpg",
   "/img/main/GarlicGingerGingerGarlic.jpg",
];
export const ImageListLensArt = [
   "/img/main/ArtRoom.jpg",
   "/img/main/Rollers.jpg",
   "/img/main/PostTops.jpg",
   "/img/main/Tracts.jpg",
   "/img/main/RainbowOffice.jpg",
   "/img/main/Shadow.jpg",
   "/img/main/ClothesRail.jpg",
   "/img/main/Nope.jpg",
   "/img/main/FruitAndVeg.jpg",
   "/img/main/LightSwitch.jpg",
   "/img/main/MysteryKnob.jpg",
   "/img/main/CrocksLineUp.jpg",
   "/img/main/UnderTheSea.jpg",
   "/img/main/PenarthPierDetail.jpg",
   "/img/main/Monitor.jpg",
   "/img/main/Table.jpg",
   "/img/main/Coffee.jpg",
   "/img/main/Grave.jpg",
   "/img/main/PinkWhiteDetail.jpg",
   "/img/main/Nope.jpg",
   "/img/main/20T.jpg",
   "/img/main/OldTrainDetail.jpg",
   "/img/main/Fire-01.jpg",
   "/img/main/FireplaceDetail.jpg",
   "/img/main/Kindling-01.jpg",
   "/img/main/Kindling-02.jpg",
   "/img/main/Kindling-03.jpg",
   "/img/main/Wine.jpg",
];

export const ImageListCardiff = [
   "/img/main/Abstract.jpg",
   "/img/main/WhiteLine.jpg",
   "/img/main/CoatHangers.jpg",
   "/img/main/Feet.jpg",
   "/img/main/StairsCloseUp.jpg",
   "/img/main/Stairs.jpg",
   "/img/main/Seat.jpg",
];
export const ImageListNeon = [
   "/img/main/NeonSqiqqle1.jpg",
   "/img/main/NeonSqiqqle2.jpg",
   "/img/main/NeonSqiqqle3.jpg",
   "/img/main/NeonSqiqqle4.jpg",
];
export const ImageListWarm = [
   "/img/main/Warm2.jpg",
   "/img/main/Warm3.jpg",
   "/img/main/Warm4.jpg",
   "/img/main/Warm5.jpg",
];
export const ImageListWorthing = [
   "/img/main/ChipShop.jpg",
   "/img/main/BackOfHouses.jpg",
   "/img/main/PierBlueGlass.jpg",
   "/img/main/PierCafeOutside.jpg",
   "/img/main/PierKitchen.jpg",
   "/img/main/PierLampposts.jpg",
   "/img/main/LamppostThroughWindow.jpg",
   "/img/main/PierRedWindow.jpg",
   "/img/main/PierSeat.jpg",
   "/img/main/PierSingleLamppost.jpg",
   "/img/main/PierWindow.jpg",
   "/img/main/PierYellowGlass.jpg",
];
