jpegoptim -S 5 -s -d blur Abstract.jpg
jpegoptim -S 5 -s -d blur Arches.jpg
jpegoptim -S 5 -s -d blur ArcLight.jpg
jpegoptim -S 5 -s -d blur BackOfHouses.jpg
jpegoptim -S 5 -s -d blur Banister.jpg
jpegoptim -S 5 -s -d blur Beach.jpg
jpegoptim -S 5 -s -d blur BeachLong.jpg
jpegoptim -S 5 -s -d blur Blur.jpg
jpegoptim -S 5 -s -d blur BronzeChairs.jpg
jpegoptim -S 5 -s -d blur BuildingSite.jpg
jpegoptim -S 5 -s -d blur ChipShop.jpg
jpegoptim -S 5 -s -d blur CoatHangers.jpg
jpegoptim -S 5 -s -d blur Coffee.jpg
jpegoptim -S 5 -s -d blur Craz.jpg
jpegoptim -S 5 -s -d blur DarkAndRed.jpg
jpegoptim -S 5 -s -d blur DoorCeiling.jpg
jpegoptim -S 5 -s -d blur DressColour.jpg
jpegoptim -S 5 -s -d blur DrWhoSet.jpg
jpegoptim -S 5 -s -d blur Ediface.jpg
jpegoptim -S 5 -s -d blur element.jpg
jpegoptim -S 5 -s -d blur Feet.jpg
jpegoptim -S 5 -s -d blur GetOutaHJere.jpg
jpegoptim -S 5 -s -d blur Grave2.jpg
jpegoptim -S 5 -s -d blur Grave.jpg
jpegoptim -S 5 -s -d blur Green.jpg
jpegoptim -S 5 -s -d blur LamppostThroughWindow.jpg
jpegoptim -S 5 -s -d blur Large_cimg0573.jpg
jpegoptim -S 5 -s -d blur Light.jpg
jpegoptim -S 5 -s -d blur LightSwitch.jpg
jpegoptim -S 5 -s -d blur Lines.jpg
jpegoptim -S 5 -s -d blur Monitor.jpg
jpegoptim -S 5 -s -d blur MysteryDalek.jpg
jpegoptim -S 5 -s -d blur MysteryKnob.jpg
jpegoptim -S 5 -s -d blur NeonSqiqqle1.jpg
jpegoptim -S 5 -s -d blur NeonSqiqqle2.jpg
jpegoptim -S 5 -s -d blur NeonSqiqqle3.jpg
jpegoptim -S 5 -s -d blur NeonSqiqqle4.jpg
jpegoptim -S 5 -s -d blur NewZealandShadow.jpg
jpegoptim -S 5 -s -d blur Paulonia.jpg
jpegoptim -S 5 -s -d blur PierBlueGlass.jpg
jpegoptim -S 5 -s -d blur PierCafeOutside.jpg
jpegoptim -S 5 -s -d blur PierKitchen.jpg
jpegoptim -S 5 -s -d blur PierLampposts.jpg
jpegoptim -S 5 -s -d blur PierRedWindow.jpg
jpegoptim -S 5 -s -d blur PierSeat.jpg
jpegoptim -S 5 -s -d blur PierSingleLamppost.jpg
jpegoptim -S 5 -s -d blur PierWindow.jpg
jpegoptim -S 5 -s -d blur PierYellowGlass.jpg
jpegoptim -S 5 -s -d blur Pillbox.jpg
jpegoptim -S 5 -s -d blur Pink.jpg
jpegoptim -S 5 -s -d blur SantaDalek.jpg
jpegoptim -S 5 -s -d blur SeaSky.jpg
jpegoptim -S 5 -s -d blur Seat.jpg
jpegoptim -S 5 -s -d blur Sexism.jpg
jpegoptim -S 5 -s -d blur SmokeyLight.jpg
jpegoptim -S 5 -s -d blur StairsCloseUp.jpg
jpegoptim -S 5 -s -d blur Stairs.jpg
jpegoptim -S 5 -s -d blur Starlings.jpg
jpegoptim -S 5 -s -d blur Sunset.jpg
jpegoptim -S 5 -s -d blur Table.jpg
jpegoptim -S 5 -s -d blur TreeArch.jpg
jpegoptim -S 5 -s -d blur UnderTheSea.jpg
jpegoptim -S 5 -s -d blur Wall.jpg
jpegoptim -S 5 -s -d blur Warm2.jpg
jpegoptim -S 5 -s -d blur Warm3.jpg
jpegoptim -S 5 -s -d blur Warm4.jpg
jpegoptim -S 5 -s -d blur Warm5.jpg
jpegoptim -S 5 -s -d blur WhiteLine.jpg
jpegoptim -S 5 -s -d blur WindscreenSunset.jpg
